
-- Insert January crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Carrot', NULL, '15–20°C', 'January to February', 'April to May', 'Full Sun', 'Moderate, keep soil moist', 'Carrots are root vegetables rich in beta-carotene and vitamins. They grow well in loose, well-drained soil.', 'January', NULL),
('Spinach', NULL, '10–20°C', 'January', 'February to March', 'Partial to Full Sun', 'Frequent light watering', 'Spinach is a fast-growing leafy green packed with iron and nutrients. Prefers cool weather and moist soil.', 'January', NULL),
('Onion', NULL, '12–24°C', 'January', 'May to June', 'Full Sun', 'Low to moderate', 'Onions are bulb crops used in nearly every cuisine. Require well-drained soil and plenty of sun.', 'January', NULL),
('Beetroot', NULL, '10–25°C', 'January', 'March to April', 'Full Sun', 'Moderate', 'Beetroot is a nutritious root crop with high iron content. Grows best in cool weather and loose soil.', 'January', NULL),
('Peas', NULL, '13–18°C', 'December to January', 'March', 'Full Sun', 'Moderate', 'Peas are nitrogen-fixing legumes that improve soil health and are excellent for cold-season planting.', 'January', NULL),
('Mustard Greens', NULL, '10–25°C', 'December to January', 'February to March', 'Full Sun', 'Moderate', 'Mustard greens are pungent leafy vegetables high in vitamin C and antioxidants, thriving in winter.', 'January', NULL),
('Cauliflower', NULL, '15–20°C', 'December to January', 'February to April', 'Full Sun', 'Moderate', 'Cauliflower forms edible flower heads and needs cool climates and consistent moisture to thrive.', 'January', NULL),
('Garlic', NULL, '10–20°C', 'November to January', 'April to May', 'Full Sun', 'Low to Moderate', 'Garlic is a hardy bulbous plant with medicinal and culinary uses, planted in winter for spring harvest.', 'January', NULL),
('Lettuce', NULL, '12–20°C', 'January', 'February to March', 'Partial Sun', 'Frequent light watering', 'Lettuce is a fast-growing leafy green ideal for salads. Thrives in cool temperatures and moist soil.', 'January', NULL),
('Radish', NULL, '10–18°C', 'January', 'February', 'Full Sun', 'Moderate', 'Radish is a fast-maturing root crop ideal for winter gardens, with crisp texture and peppery taste.', 'January', NULL);

-- Insert February crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Tomato', NULL, '18–27°C', 'February to March', 'April to June', 'Full Sun', 'Regular, keep soil moist but not soggy', 'Tomatoes are popular warm-season crops grown for their juicy fruits. They need support and regular feeding.', 'February', NULL),
('Brinjal (Eggplant)', NULL, '20–30°C', 'February to March', 'May to July', 'Full Sun', 'Moderate, avoid waterlogging', 'Brinjal is a heat-loving vegetable used widely in Indian cuisine. Requires well-drained soil and ample sunlight.', 'February', NULL),
('Cucumber', NULL, '18–30°C', 'February to March', 'May to June', 'Full Sun', 'High, keep soil consistently moist', 'Cucumbers are vining plants that thrive in warm climates, producing crisp, hydrating fruits ideal for summer.', 'February', NULL),
('Chili', NULL, '20–30°C', 'February to March', 'June to July', 'Full Sun', 'Moderate, let soil dry slightly between watering', 'Chilies are spicy fruits that thrive in warm climates. They require sun, warmth, and moderate water.', 'February', NULL),
('Pumpkin', NULL, '20–30°C', 'February to March', 'June to July', 'Full Sun', 'Moderate to high, especially during fruiting', 'Pumpkins are large vine crops requiring ample space and sun. They need consistent moisture for proper growth.', 'February', NULL),
('Bottle Gourd', NULL, '20–30°C', 'February to March', 'May to June', 'Full Sun', 'High, especially during flowering and fruiting', 'Bottle gourds are summer climbers producing long, edible fruits. Best grown on trellises with regular watering.', 'February', NULL),
('Okra (Lady Finger)', NULL, '22–30°C', 'February to April', 'May to July', 'Full Sun', 'Moderate', 'Okra is a warm-season vegetable rich in fiber. Grows well in warm climates with loose, fertile soil.', 'February', NULL),
('Coriander', NULL, '15–25°C', 'February to March', 'April to May', 'Partial to Full Sun', 'Regular but light watering', 'Coriander is a fast-growing herb used in cooking. Prefers cool weather and well-drained moist soil.', 'February', NULL),
('French Beans', NULL, '16–27°C', 'February to March', 'April to May', 'Full Sun', 'Moderate, especially during flowering', 'French beans are quick-growing legumes that produce tender pods. They thrive in warm, sunny conditions.', 'February', NULL),
('Turnip', NULL, '10–20°C', 'January to February', 'April to May', 'Full Sun', 'Moderate', 'Turnips are cool-season root vegetables grown for their white roots and greens. Best in loose, rich soil.', 'February', NULL);

-- Insert March crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Bitter Gourd', NULL, '25–30°C', 'March to April', 'June to July', 'Full Sun', 'Moderate, increase during flowering', 'Bitter gourd is a tropical vine grown for its bitter, nutrient-rich fruits. It grows well in warm climates with support.', 'March', NULL),
('Snake Gourd', NULL, '25–30°C', 'March to April', 'June to July', 'Full Sun', 'Regular, especially during dry spells', 'Snake gourd is a fast-growing vine that produces long, edible fruits. It thrives in warm weather and on trellises.', 'March', NULL),
('Cluster Beans (Guar)', NULL, '25–35°C', 'March to April', 'June to July', 'Full Sun', 'Low to moderate', 'Cluster beans are drought-tolerant legumes that thrive in hot climates. They are rich in fiber and easy to grow.', 'March', NULL),
('Amaranth (Chaulai)', NULL, '25–30°C', 'March to June', '30–45 days after sowing', 'Full Sun', 'Light, frequent watering', 'Amaranth is a leafy green rich in iron and calcium. It is a heat-tolerant plant with quick growth.', 'March', NULL),
('Yardlong Beans (Bora)', NULL, '20–30°C', 'March to May', '60–75 days after sowing', 'Full Sun', 'Moderate', 'Yardlong beans are vining legumes known for their long pods. They require warm weather and trellis support.', 'March', NULL),
('Sponge Gourd (Luffa)', NULL, '25–32°C', 'March to April', 'June to July', 'Full Sun', 'Moderate to high', 'Sponge gourd is a summer vegetable with tender fruits. It requires a trellis and well-drained fertile soil.', 'March', NULL),
('Turmeric', NULL, '20–30°C', 'March to April', 'January (next year)', 'Partial to Full Sun', 'Moderate, needs more in hot weather', 'Turmeric is a rhizome crop grown for its medicinal and culinary use. It requires long growing duration and warm climate.', 'March', NULL),
('Ash Gourd', NULL, '24–30°C', 'March to May', 'June to August', 'Full Sun', 'Moderate to high', 'Ash gourd is a vine crop producing large waxy fruits. It thrives in heat and requires space to spread.', 'March', NULL),
('Cowpea', NULL, '20–30°C', 'March to May', 'June to July', 'Full Sun', 'Moderate', 'Cowpea is a heat-tolerant legume that fixes nitrogen. It can be grown for both pods and dry beans.', 'March', NULL),
('Sweet Corn', NULL, '21–27°C', 'March to April', 'June to July', 'Full Sun', 'High during flowering and cob formation', 'Sweet corn is a cereal crop grown for its tender cobs. Requires fertile soil, space, and frequent watering.', 'March', NULL);

-- Insert April crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Lady Finger (Okra)', NULL, '22–30°C', 'April to June', 'July to September', 'Full Sun', 'Moderate', 'Lady finger is a warm-season crop that produces tender green pods. It requires well-drained soil and full sunlight.', 'April', NULL),
('Cucumber', NULL, '18–30°C', 'April to May', 'June to July', 'Full Sun', 'High, keep soil consistently moist', 'Cucumbers are warm-weather vines producing refreshing fruits. Ideal for summer salads and best grown on trellises.', 'April', NULL),
('Sponge Gourd (Luffa)', NULL, '25–32°C', 'April to May', 'July to August', 'Full Sun', 'Moderate to high', 'Sponge gourd produces long green fruits and thrives in warm weather with adequate sunlight and support.', 'April', NULL),
('Bitter Gourd', NULL, '25–30°C', 'April to May', 'July to August', 'Full Sun', 'Moderate', 'Bitter gourd is a summer vine crop that produces bitter, medicinal fruits. Grows well with support and warm climate.', 'April', NULL),
('Bottle Gourd', NULL, '20–30°C', 'April to June', 'July to September', 'Full Sun', 'High, especially during fruiting', 'Bottle gourds are quick-growing vines producing long, light green fruits. Great for summer kitchens and juice.', 'April', NULL),
('Watermelon', NULL, '24–32°C', 'April', 'July to August', 'Full Sun', 'High, especially during fruit formation', 'Watermelons are summer fruits grown from vines. Require space, heat, and regular watering to produce sweet juicy fruits.', 'April', NULL),
('Muskmelon', NULL, '25–35°C', 'April to May', 'July to August', 'Full Sun', 'Moderate to high', 'Muskmelons are warm-season climbers known for their sweet, fragrant fruits. Thrive in heat and require loose soil.', 'April', NULL),
('Chili', NULL, '20–30°C', 'April to May', 'August to October', 'Full Sun', 'Moderate, avoid overwatering', 'Chili plants produce spicy fruits and grow well in summer. They need sun, warmth, and moderate irrigation.', 'April', NULL),
('Brinjal (Eggplant)', NULL, '20–30°C', 'April to May', 'July to September', 'Full Sun', 'Moderate, avoid waterlogging', 'Brinjal is a popular vegetable that thrives in warm conditions. Requires fertile soil and regular feeding.', 'April', NULL),
('Cluster Beans (Guar)', NULL, '25–35°C', 'April to June', 'July to September', 'Full Sun', 'Low to moderate', 'Cluster beans are heat-loving legumes that grow well in arid conditions. A great summer vegetable rich in fiber.', 'April', NULL);

-- Insert May crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Amaranth (Chaulai)', NULL, '25–35°C', 'May to July', '30–45 days after sowing', 'Full Sun', 'Light, frequent watering', 'Amaranth is a fast-growing leafy green loaded with nutrients. It thrives in summer heat and is easy to harvest frequently.', 'May', NULL),
('Okra (Lady Finger)', NULL, '22–35°C', 'May to July', 'July to September', 'Full Sun', 'Moderate', 'Okra is a summer crop that produces tender pods. It grows best in warm weather and well-drained soil.', 'May', NULL),
('Cluster Beans (Guar)', NULL, '25–35°C', 'May to June', 'August to September', 'Full Sun', 'Low to moderate', 'Cluster beans are drought-resistant legumes. Ideal for summer farming with minimal watering needs.', 'May', NULL),
('Bottle Gourd', NULL, '20–30°C', 'May to July', 'August to September', 'Full Sun', 'High, especially during flowering and fruiting', 'Bottle gourd is a vigorous vine producing long, light-green fruits. Best suited for summer cultivation on trellises.', 'May', NULL),
('Bitter Gourd', NULL, '25–30°C', 'May to June', 'August to September', 'Full Sun', 'Moderate', 'Bitter gourd is a nutrient-rich summer vegetable known for its medicinal value. Needs trellis support and warm conditions.', 'May', NULL),
('Sponge Gourd', NULL, '25–32°C', 'May to June', 'August to September', 'Full Sun', 'Moderate to high', 'Sponge gourd is a fast-growing summer climber with soft, edible fruits. It prefers rich soil and full sun.', 'May', NULL),
('Yardlong Beans', NULL, '25–35°C', 'May to June', 'August to September', 'Full Sun', 'Moderate', 'Yardlong beans are summer legumes producing very long, tender pods. They climb vigorously and need regular harvesting.', 'May', NULL),
('Corn (Maize)', NULL, '20–32°C', 'May to June', 'September to October', 'Full Sun', 'High during tasseling and cob formation', 'Maize is a staple summer crop grown for its grain or green cobs. It requires space, warmth, and plenty of water.', 'May', NULL),
('Turmeric', NULL, '20–30°C', 'May to June', 'January (next year)', 'Partial to Full Sun', 'Moderate to high', 'Turmeric is a rhizome grown for its anti-inflammatory properties. Needs a long warm growing season and consistent moisture.', 'May', NULL),
('Sweet Potato', NULL, '24–30°C', 'May to July', 'September to November', 'Full Sun', 'Moderate', 'Sweet potatoes are nutrient-rich tubers that thrive in warm climates. They need loose soil and minimal care once established.', 'May', NULL);

-- Insert June crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Rice', NULL, '25–35°C', 'June to July', 'October to November', 'Full Sun', 'Very high, requires flooded fields initially', 'Rice is a staple food crop grown in waterlogged fields. It thrives in hot, humid conditions and requires high water availability.', 'June', NULL),
('Maize (Corn)', NULL, '20–32°C', 'June to July', 'October to November', 'Full Sun', 'High, especially during tasseling and cob formation', 'Maize is a fast-growing cereal crop needing fertile soil and regular watering. Grown widely during kharif season.', 'June', NULL),
('Soybean', NULL, '25–30°C', 'June to July', 'October to November', 'Full Sun', 'Moderate, avoid waterlogging', 'Soybeans are leguminous crops high in protein and oil. They improve soil fertility by fixing nitrogen.', 'June', NULL),
('Pigeon Pea (Arhar/Tur)', NULL, '26–30°C', 'June to July', 'November to December', 'Full Sun', 'Moderate, drought-tolerant once established', 'Pigeon peas are long-duration legumes grown for their protein-rich seeds. Require warm weather and less water.', 'June', NULL),
('Green Gram (Moong)', NULL, '25–35°C', 'June to July', 'August to September', 'Full Sun', 'Low to moderate', 'Green gram is a short-duration legume crop that matures quickly. It''s rich in protein and good for intercropping.', 'June', NULL),
('Black Gram (Urad)', NULL, '25–35°C', 'June to July', 'September to October', 'Full Sun', 'Low to moderate', 'Black gram is a nitrogen-fixing crop widely used in Indian cooking. Grows well in warm, humid conditions.', 'June', NULL),
('Groundnut (Peanut)', NULL, '25–30°C', 'June to July', 'October to November', 'Full Sun', 'Moderate, avoid excess moisture during flowering', 'Groundnuts are oilseed crops grown in sandy-loamy soil. Require warm weather and moderate rainfall.', 'June', NULL),
('Sesame (Til)', NULL, '25–35°C', 'June to July', 'September to October', 'Full Sun', 'Low, drought-tolerant', 'Sesame is a drought-resistant oilseed crop. It requires minimal water and grows well in light, well-drained soil.', 'June', NULL),
('Sorghum (Jowar)', NULL, '25–30°C', 'June to July', 'October to November', 'Full Sun', 'Low to moderate, drought-tolerant', 'Sorghum is a hardy cereal crop ideal for dry regions. It grows well with minimal inputs and provides food and fodder.', 'June', NULL),
('Pearl Millet (Bajra)', NULL, '28–32°C', 'June to July', 'September to October', 'Full Sun', 'Low, drought-tolerant', 'Pearl millet is a resilient crop ideal for arid zones. It produces nutrient-rich grains and grows quickly with less water.', 'June', NULL);

-- Insert July crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Soybean', NULL, '25–30°C', 'June–August', 'October–November', 'Full Sun', 'Weekly, more during flowering', 'Protein-rich oilseed, supports soil nitrogen fixation. Soybean improves soil fertility while providing oil and protein-rich food. Widely used in processed foods and livestock feed.', 'July', NULL),
('Maize (Corn)', NULL, '21–27°C', 'June–July', 'September–October', 'Full Sun', 'Every 2–3 days', 'Versatile grain and fodder crop planted early monsoon; sunlight-intensive. Maize is widely used for food, fodder, and industrial products. Prefers well-drained soils and consistent sun exposure for optimal yields.', 'July', NULL),
('Groundnut', NULL, '20–30°C', 'June–July', 'September–October', 'Full Sun', 'Moderate, avoid waterlogging', 'Oilseed and snack crop; fixes nitrogen and used in crop rotations. Groundnut (peanut) is rich in healthy fats and improves soil health. Popular as a cash crop and often intercropped with legumes.', 'July', NULL),
('Pigeon Pea (Tur/Arhar)', NULL, '20–30°C', 'June–July', 'September–October', 'Full Sun', 'Low to moderate', 'Arhar (pigeon pea) is a major Kharif legume crop, rich in protein and drought-tolerant. Its deep roots help it withstand dry spells, making it vital for dryland farming and a key ingredient in Indian dals.', 'July', NULL),
('Green Gram (Moong)', NULL, '25–32°C', 'June–July', 'September–October', 'Full Sun', 'Low, drought-tolerant', 'Easy-to-grow pulse needing minimal water; staple in rotation systems. Moong (green gram) enriches the soil and offers quick returns. Ideal for intercropping with cereals and oilseeds', 'July', NULL),
('Sorghum (Jowar)', NULL, '25–32°C', 'June–July', 'October–November', 'Full Sun', 'Moderate, drought-resistant', 'Millets well-suited to semi-arid conditions, rich in fiber and protein. Grown in poor soils with low water needs, they help fight climate stress. Excellent for diabetic and gluten-free diets.', 'July', NULL),
('Lady Finger (Okra)', NULL, '24–30°C', 'June–July', 'August–November', 'Full Sun', 'Twice weekly', 'Heat-loving vegetable; pods harvested regularly for continuous yield. Bhindi (okra) thrives in warm weather and well-drained soil. Regular harvesting boosts production and keeps plants productive.', 'July', NULL),
('Rice', NULL, '20–35°C', 'June–July', 'September–October', 'Full Sun', 'Flooded fields', 'Rice is a staple food crop that grows best in hot, humid climates with abundant water. It is typically cultivated in waterlogged fields, producing grains that feed billions worldwide.', 'July', NULL),
('Black Gram (Urad)', NULL, '25–33°C', 'June–July', 'September–October', 'Full Sun', 'Moderate', 'Common pulse used in dals and fermented foods in India. Urad (black gram) is protein-rich and often used in idlis and dosas. Fixes nitrogen in the soil and boosts fertility.', 'July', NULL),
('Pearl Millet (Bajra)', NULL, '25–35°C', 'June–July', 'October–November', 'Full Sun', 'Low to moderate', 'Millet, particularly Bajra (Pearl Millet), is a nutrient-rich grain packed with iron, magnesium, and fiber. Highly resilient to heat and drought, it’s perfect for dryland farming and supports a healthy diet with its energy-boosting and digestive benefits.','July', NULL);

--Insert August crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Capsicum (Bell Pepper)', NULL, '20–30°C', 'June to August', 'October to December', 'Full sunlight', 'Moderate', 'Capsicum grows best in warm, humid weather. August sowing gives strong plants with good fruiting in autumn.', 'August', NULL),
('Onion', NULL, '20–25°C', 'August to October', 'January to March', 'Full sunlight', 'Low to moderate', 'Onion is a widely grown bulb vegetable valued for its pungent flavor and culinary versatility. It thrives in well-drained soil and requires moderate watering.', 'August', NULL),
('Lettuce', NULL, '15–25°C', 'August to October', 'October to December', 'Partial shade', 'Light, shallow watering', 'Lettuce is a cool-season leafy vegetable, ideal for salads. It prefers mild temperatures and consistent moisture.', 'August', NULL),
('Carrot', NULL, '16–25°C', 'August to November', 'December to February', 'Full sunlight', 'Moderate', 'Carrots are nutritious root vegetables rich in beta-carotene. They thrive in loose, well-drained soil.', 'August', NULL),
('Maize (Corn)', NULL, '21–27°C', 'July to August', 'November to December', 'Full sunlight', 'Moderate', 'Maize is a versatile cereal crop grown during monsoon season. It requires good sunlight and proper spacing.', 'August', NULL),
('Spinach', NULL, '15–30°C', 'August to February', '4–6 weeks after sowing', 'Partial to full sunlight', 'Moderate, keep soil moist', 'Spinach is a leafy green vegetable rich in iron and vitamins. It grows quickly and prefers cooler climates.', 'August', NULL),
('Garlic', NULL, '15–25°C', 'August to November', 'February to April', 'Full sunlight', 'Light but regular', 'Garlic is a flavorful bulb crop known for its medicinal properties. It grows well in loose, fertile soil.', 'August', NULL),
('Brinjal (Eggplant)', NULL, '20–30°C', 'July to August', 'October to February', 'Full sunlight', 'Moderate, consistent moisture', 'Brinjal is a popular vegetable crop grown in warm climates. It requires fertile soil and regular care.', 'August', NULL),
('Fenugreek (Methi)', NULL, '15–25°C', 'August to March', '3–4 weeks for leaves, 60–90 days for seeds', 'Full sunlight', 'Light, every 2–3 days', 'Fenugreek is a fast-growing herb used for both leaves and seeds. It grows well in well-drained soil.', 'August', NULL),
('French Beans', NULL, '15–30°C', 'July to September', '50–60 days after sowing', 'Full sunlight', 'Regular watering', 'French beans are nutritious legumes grown for their tender pods. They grow well in moderate temperatures.', 'August', NULL);

-- Insert September crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Spinach', 'Spinacia oleracea', '15–20°C', 'September–November', 'October–January', 'Full sun to partial shade', 'Moderate', 'Spinach is a fast-growing, nutrient-rich leafy vegetable. It grows well in cool weather and thrives in moist, fertile soil.', 'September', NULL),
('Mustard Greens', 'Brassica juncea', '10–25°C', 'September–November', 'November–January', 'Full sun to partial shade', 'Moderate, keep soil moist', 'Mustard greens have a fast-growing, peppery-flavored leafy vegetable rich in cool weather. Low-maintenance.', 'September', NULL),
('Garlic', 'Allium sativum', '12–20°C', 'September–October', 'March–May', 'Full sun', 'Light, avoid waterlogging', 'Garlic is a flavorful bulb crop known for its strong aroma and medicinal properties. Rich in antioxidants and easy to grow.', 'September', NULL),
('Lettuce', 'Lactuca sativa', '10–20°C', 'September–December', 'October–January', 'Full sun', 'Frequent, keep soil moist', 'Lettuce is a cool-season leafy vegetable. It requires regular watering and thrives in loose, well-drained soil.', 'September', NULL),
('Beetroot', 'Beta vulgaris', '15–25°C', 'September–November', 'December–February', 'Full sun', 'Regular', 'Beetroot grows best in cooler months, producing sweet, earthy roots and nutritious edible greens.', 'September', NULL),
('Radish', 'Raphanus sativus', '10–25°C', 'September–December', '3–4 weeks after sowing', 'Full sun', 'Moderate', 'Radishes are quick-growing root vegetables that are easy to cultivate, ideal for beginner gardeners.', 'September', NULL),
('Cauliflower', 'Brassica oleracea var. botrytis', '15–20°C', 'September–October', 'December–February', 'Full sun', 'Regular', 'Cauliflower is a cool-season crop that develops dense, edible flower heads. It requires consistent moisture.', 'September', NULL),
('Carrot', 'Daucus carota', '10–25°C', 'September–November', 'December–February', 'Full sun', 'Moderate', 'Carrots are nutritious root vegetables packed with beta-carotene. They thrive in loose, well-drained soil.', 'September', NULL),
('Broccoli', 'Brassica oleracea var. italica', '15–20°C', 'September–October', 'December–February', 'Full sun', 'Regular', 'Broccoli is a nutrient-dense vegetable that thrives in cool climates. Packed with vitamins and minerals.', 'September', NULL),
('Onion', 'Allium cepa', '13–25°C', 'September–October', 'February–April', 'Full sun', 'Moderate', 'Onion is a widely grown bulb vegetable valued for its pungent flavor and culinary versatility.', 'September', NULL);

-- Insert October crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Broccoli', 'Brassica oleracea var. italica', '13–22°C', 'October–November', 'February–March', 'Full sun', 'Twice a week', 'Broccoli is a nutrient-dense vegetable that thrives in cool climates. Packed with vitamins and minerals.', 'October', NULL),
('Mustard', 'Brassica juncea', '20–25°C', 'October–November', 'February–March', 'Full sun', 'Once in 5–7 days', 'Mustard is a fast-growing oilseed crop, widely cultivated during rabi season. It thrives in cool weather and well-drained soil.', 'October', NULL),
('Spinach', 'Spinacia oleracea', '15–25°C', 'September–November', 'November–January', 'Full sun to partial shade', '2–3 times a week', 'Spinach is a fast-growing, nutrient-dense leafy vegetable rich in iron and vitamins. It thrives in moist, fertile soil.', 'October', NULL),
('Peas', 'Pisum sativum', '5–20°C', 'October–November', 'January–February', 'Full to full sun', 'Twice a week', 'Green peas thrive in cool weather, producing sweet, tender pods enjoyed fresh or cooked. They are a gardener’s favorite.', 'October', NULL),
('Cabbage', 'Brassica oleracea var. capitata', '15–20°C', 'October–December', 'January–March', 'Full sun', '2–3 times a week', 'Cabbage is a compact, cool-season leafy vegetable rich in vitamins and antioxidants. It grows well in winter conditions.', 'October', NULL),
('Carrot', 'Daucus carota', '15–25°C', 'October–November', 'January–February', 'Full sun', 'Twice a week', 'Carrots are nutritious root vegetables packed with beta-carotene and minerals. They thrive in loose, well-drained soil.', 'October', NULL),
('Garlic', 'Allium sativum', '12–24°C', 'October–December', 'March–April', 'Full sun', 'Once a week', 'Garlic is a flavorful bulb crop known for its strong aroma and medicinal properties. Rich in antioxidants and easy to grow.', 'October', NULL),
('Lettuce', 'Lactuca sativa', '12–20°C', 'October–December', 'December–February', 'Partial to full sun', '2–3 times per week', 'Lettuce is a cool-season leafy vegetable. It requires regular watering and thrives in loose, well-drained soil.', 'October', NULL),
('Onion', 'Allium cepa', '20–25°C', 'October–December', 'March–April', 'Full sun', 'Once every 4–5 days', 'Onion is a widely grown bulb vegetable valued for its pungent flavor and culinary versatility.', 'October', NULL),
('Fenugreek (Methi)', 'Trigonella foenum-graecum', '15–25°C', 'October–November', 'December–January', 'Full sun', '2–3 times per week', 'Fenugreek is a versatile herb grown for its flavorful leaves and seeds, used in both vegetable and spice form. Rich in nutrients.', 'October', NULL);

-- Insert November crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Radish', 'Raphanus sativus', '10–25°C', 'October–January', 'November–February', 'Full sun', 'Frequent and regular', 'Radishes are quick-growing root vegetables that are easy to cultivate, ideal for beginner gardeners.', 'November', NULL),
('Spinach', 'Spinacia oleracea', '10–25°C', 'October–February', 'November–March', 'Full to partial sun', 'Frequent, light watering', 'Spinach is a fast-growing leafy vegetable rich in iron and vitamins. It thrives in moist, fertile soil.', 'November', NULL),
('Onion', 'Allium cepa', '13–25°C', 'October–December', 'February–April', 'Full sun', 'Moderate', 'Onion is a widely grown bulb vegetable valued for its pungent flavor and culinary versatility.', 'November', NULL),
('Mustard Greens', 'Brassica juncea', '10–25°C', 'October–December', 'January–March', 'Full sun', 'Moderate', 'Mustard greens have a fast-growing, peppery-flavored leafy vegetable rich in cool weather. Low-maintenance.', 'November', NULL),
('Coriander', 'Coriandrum sativum', '15–25°C', 'October–February', 'November–March', 'Full sun', 'Light, consistent watering', 'Coriander is an aromatic herb valued for its fresh leaves and seeds, widely used in cooking.', 'November', NULL),
('Lettuce', 'Lactuca sativa', '10–20°C', 'October–December', 'December–February', 'Full to partial sun', 'Regular', 'Lettuce is a cool-season leafy vegetable. It requires regular watering and thrives in loose, well-drained soil.', 'November', NULL),
('Fenugreek (Methi)', 'Trigonella foenum-graecum', '10–25°C', 'October–February', 'December–March', 'Full sun', 'Light and consistent', 'Fenugreek is a versatile herb grown for its flavorful leaves and seeds, used in both vegetable and spice form. Rich in nutrients.', 'November', NULL),
('Garlic', 'Allium sativum', '10–25°C', 'October–November', 'March–May', 'Full sun', 'Light watering', 'Garlic is a flavorful bulb crop known for its strong aroma and medicinal properties. Rich in antioxidants.', 'November', NULL),
('Beetroot', 'Beta vulgaris', '10–25°C', 'October–November', 'December–February', 'Full to partial sun', 'Moderate, consistent', 'Beetroot grows best in cooler months, producing sweet, earthy roots and nutritious edible greens.', 'November', NULL),
('Carrot', 'Daucus carota', '10–25°C', 'October–December', 'January–March', 'Full sun', 'Regular, keep soil moist', 'Carrots are nutritious root vegetables packed with beta-carotene and minerals. They thrive in loose, well-drained soil.', 'November', NULL);

-- Insert December crops
INSERT INTO public.grow_guide_crops (crop_name, scientific_name, ideal_temperature, sowing_months, harvest_months, sunlight_requirement, watering_frequency, description, month, image_url) VALUES
('Peas', 'Pisum sativum', '5–20°C', 'October–December', 'February–April', 'Full sun', 'Twice a week', 'Green peas thrive in cool weather, producing sweet, tender pods enjoyed fresh or cooked.', 'December', NULL),
('Garlic', 'Allium sativum', '10–20°C', 'October–December', 'March–May', 'Full sun', 'Once a week', 'Garlic is a flavorful bulb crop known for its strong aroma and medicinal properties. Rich in antioxidants.', 'December', NULL),
('Carrot', 'Daucus carota', '10–25°C', 'November–December', 'February–March', 'Full sun', 'Regular', 'Carrots are nutritious root vegetables packed with beta-carotene and minerals. They thrive in loose, well-drained soil.', 'December', NULL),
('Radish', 'Raphanus sativus', '10–25°C', 'October–December', 'December–February', 'Full sun', 'Moderate watering', 'Radishes are quick-growing root vegetables that are easy to cultivate, ideal for beginner gardeners.', 'December', NULL),
('Mustard Greens', 'Brassica juncea', '10–25°C', 'October–December', 'January–March', 'Full sun', 'Moderate', 'Mustard greens have a fast-growing, peppery-flavored leafy vegetable rich in cool weather. Low-maintenance.', 'December', NULL),
('Coriander', 'Coriandrum sativum', '10–25°C', 'October–December', 'December–February', 'Full sun', 'Moderate', 'Coriander is an aromatic herb valued for its fresh leaves and seeds, widely used in cooking.', 'December', NULL),
('Lettuce', 'Lactuca sativa', '10–20°C', 'September–December', 'December–February', 'Partial sun', 'Regular', 'Lettuce is a cool-season leafy vegetable. It requires regular watering and thrives in loose, well-drained soil.', 'December', NULL),
('Spinach', 'Spinacia oleracea', '10–25°C', 'October–December', 'December–February', 'Full to partial sun', 'Frequent', 'Spinach is a fast-growing leafy vegetable rich in iron and vitamins. It thrives in moist, fertile soil.', 'December', NULL),
('Onion', 'Allium cepa', '13–25°C', 'December–January', 'May–June', 'Full sun', 'Low, once a week', 'Onion is a widely grown bulb vegetable valued for its pungent flavor and culinary versatility.', 'December', NULL),
('Fenugreek (Methi)', 'Trigonella foenum-graecum', '10–25°C', 'October–December', 'December–February', 'Full sun', 'Light watering every 2–3 days', 'Fenugreek is a versatile herb grown for its flavorful leaves and seeds, used in both vegetable and spice form. Rich in nutrients.', 'December', NULL);
